from pathlib import Path
path = Path('app/order-of-service/MemorialCardPreview.tsx')
text = path.read_text()
old = """const scriptGreatVibes = Great_Vibes({ subsets: ['latin'], weight: '400' });\nconst scriptParisienne = Parisienne({ subsets: ['latin'], weight: '400' });\nconst serifPlayfair = Playfair_Display({ subsets: ['latin'], weight: ['400', '500', '600'] });\nconst serifCinzel = Cinzel({ subsets: ['latin'], weight: ['400', '500', '600'] });\nconst sansInter = Inter({ subsets: ['latin'], weight: ['400', '500', '600'] });\nconst sansSourceSans = Source_Sans_3({ subsets: ['latin'], weight: ['400', '600'] });\n\nconst scriptFontRegistry = {\n  'great-vibes': { label: 'Great Vibes', font: scriptGreatVibes },\n  parisienne: { label: 'Parisienne', font: scriptParisienne },\n} as const;\n\nconst serifFontRegistry = {\n  playfair: { label: 'Playfair Display', font: serifPlayfair },\n  cinzel: { label: 'Cinzel', font: serifCinzel },\n} as const;\n\nconst sansFontRegistry = {\n  inter: { label: 'Inter', font: sansInter },\n  'source-sans': { label: 'Source Sans 3', font: sansSourceSans },\n} as const;\n"""
new = """const scriptGreatVibes = Great_Vibes({ subsets: [\"latin\"], weight: \"400\" });\nconst scriptParisienne = Parisienne({ subsets: [\"latin\"], weight: \"400\" });\nconst serifPlayfair = Playfair_Display({ subsets: [\"latin\"], weight: [\"400\", \"500\", \"600\"] });\nconst serifCinzel = Cinzel({ subsets: [\"latin\"], weight: [\"400\", \"500\", \"600\"] });\nconst sansInter = Inter({ subsets: [\"latin\"], weight: [\"400\", \"500\", \"600\"] });\nconst sansSourceSans = Source_Sans_3({ subsets: [\"latin\"], weight: [\"400\", \"600\"] });\n\nconst scriptFontRegistry = {\n  \"great-vibes\": { label: \"Great Vibes\", font: scriptGreatVibes },\n  parisienne: { label: \"Parisienne\", font: scriptParisienne },\n} as const;\n\nconst serifFontRegistry = {\n  playfair: { label: \"Playfair Display\", font: serifPlayfair },\n  cinzel: { label: \"Cinzel\", font: serifCinzel },\n} as const;\n\nconst sansFontRegistry = {\n  inter: { label: \"Inter\", font: sansInter },\n  \"source-sans\": { label: \"Source Sans 3\", font: sansSourceSans },\n} as const;\n"""
if old not in text:
    raise SystemExit('block not found')
text = text.replace(old, new, 1)
path.write_text(text)
